### ISSUE TITLE
Replace demonstration page video with latest functionality

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.github.io#95]
https://www.interscript.org/demonstration

Actually we should move the demonstration to the home page, no point in having a separate page.

**Comment by ronaldtse** [comment]
Thanks!

**Comment by webdev778** [comment]
https://github.com/interscript/interscript.github.io/assets/28761746/5b47a749-3b66-4468-8596-5754dc4eb6fd

I've recorded a new video of demonstration but it's too long and big to convert to gif. now I'm looking for an alternative ways to present the video on readme. the one I found is https://asciinema.org/.

**Comment by webdev778** [comment]
successfully converted to a gif. 

![Image](https://github.com/interscript/interscript.github.io/assets/28761746/4408812c-a6b1-4141-8095-e165aff45aa6)

**Comment by webdev778** [comment]
I've updated the demo video and move cosolidation of demo and home page into a new issue #100.
close this issue
